### ISSUE TITLE
Build error project

### ISSUE THREAD

**Issue by haidv1992** [whythawk/full-stack-fastapi-postgresql#10]
i am language not good, thank your support
when i build docker not running all 
it is my docker container
![image](https://user-images.githubusercontent.com/86423592/216882753-7ccb8b68-15a9-4dfc-8d0f-2ff72c41af0a.png)

and pgadmin can't login 
![image](https://user-images.githubusercontent.com/86423592/216882950-df6cfa36-21b0-4ea2-9f72-9eed0c2012df.png)

bu when i connect with navicat it connected good

![image](https://user-images.githubusercontent.com/86423592/216883179-369ef0fe-f69e-474d-83ef-9c1193bc5763.png)

 is my .env
 

DOMAIN=localhost
# DOMAIN=local.dockertoolbox.tiangolo.com
# DOMAIN=localhost.tiangolo.com
# DOMAIN=dev.thien.com

STACK_NAME=thien-com

TRAEFIK_PUBLIC_NETWORK=traefik-public
TRAEFIK_TAG=thien.com
TRAEFIK_PUBLIC_TAG=traefik-public

DOCKER_IMAGE_BACKEND=backend
DOCKER_IMAGE_CELERYWORKER=celeryworker
DOCKER_IMAGE_FRONTEND=frontend

# Backend
BACKEND_APP_MODULE=app.main:app
BACKEND_CORS_ORIGINS=http://localhost:4200
BACKEND_PRE_START_PATH=/app/prestart.sh
PROJECT_NAME=thien
SECRET_KEY=190c2051bcd209ae63c0e81c282caf4442392a610535f39aa5bb9eda31921e1a
TOTP_SECRET_KEY=changethis
FIRST_SUPERUSER=admin@thien.com
FIRST_SUPERUSER_PASSWORD=Admin@123
SMTP_TLS=True
SMTP_PORT=587
SMTP_HOST=
SMTP_USER=
SMTP_PASSWORD=
EMAILS_FROM_EMAIL=info@thien.com
EMAILS_FROM_NAME=Symona Adaro
EMAILS_TO_EMAIL=info@thien.com

USERS_OPEN_REGISTRATION=True

SENTRY_DSN=

# Flower
FLOWER_BASIC_AUTH=admin:Admin@123

# Postgres
POSTGRES_SERVER=db
POSTGRES_USER=postgres
POSTGRES_PASSWORD=changethis
POSTGRES_DB=app

# PgAdmin
PGADMIN_LISTEN_PORT=5050
PGADMIN_DEFAULT_EMAIL=admin@thien.com
PGADMIN_DEFAULT_PASSWORD=Admin@123

# Neo4j
NEO4J_SERVER=neo4j
NEO4J_USERNAME=neo4j
NEO4J_PASSWORD=changethis
NEO4J_AUTH=neo4j:changethis
NEO4J_BOLT=bolt

**Comment by turukawa** [comment]
Hi @haidv1992 

In your `.env` did you make all of these definitions active at the same time?

```
DOMAIN=localhost
DOMAIN=local.dockertoolbox.tiangolo.com
DOMAIN=localhost.tiangolo.com
DOMAIN=dev.thien.com
```

Because it should just be this (assuming this is `local` development):

```
DOMAIN=localhost
# DOMAIN=local.dockertoolbox.tiangolo.com
# DOMAIN=localhost.tiangolo.com
# DOMAIN=dev.thien.com
```

Or is that just formatted badly? Plus:

`BACKEND_CORS_ORIGINS=http://localhost:4200/`

Should be a list of strings:

`BACKEND_CORS_ORIGINS=["http://localhost:4200/"]`

**Comment by turukawa** [comment]
Problem is not being able to duplicate these errors. I imagine it's something to do with `docker` or `docker-compose` being "leaky", so your development environment has some effect. Whereas when you deploy to a clean server, it's likely to be fairly similar and with few overt opinions. But ... no idea ... sorry.

**Comment by turukawa** [comment]
Closing for lack of response.
