### ISSUE TITLE
Change tokenUrl

### ISSUE THREAD

**Issue by Choiuijin1125** [whythawk/full-stack-fastapi-postgresql#11]
Hi !

Thanks you for amazing contribution :)

I just found that we need to change app/api/deps/

`reusable_oauth2 = OAuth2PasswordBearer(tokenUrl=f"(tokenUrl=f"{settings.API_V1_STR}/login/access-token")`
->
`reusable_oauth2 = OAuth2PasswordBearer(tokenUrl=f"{settings.API_V1_STR}/login/oauth")`

Whatelse it will throw error in swagger authentication

**Comment by turukawa** [comment]
Hi @Choiuijin1125

Thanks, good catch. I'll fix that shortly. Was thinking I might do a quick refactor for SqlAlchemy 2.0 as well ...

**Comment by turukawa** [comment]
[Release 0.7.1](https://github.com/whythawk/full-stack-fastapi-postgresql/releases/tag/0.7.1) should fix this.
