### ISSUE TITLE
undefined function in /validate-email:post

### ISSUE THREAD

**Issue by FranzForstmayr** [whythawk/full-stack-fastapi-postgresql#17]
The function `verify_password_reset_token` is not defined, but used in `validate_email` endpoint.

Is this endpoint not needed anymore through the new auth scheme?

**Comment by turukawa** [comment]
Yeah, it's an artifact left over from some not-quite-completed thought. Something about an admin creating a user-account, and then the user needing to validate their email after login, but that workflow seems a bit dodgy with the new auth scheme.

There's a few functions supporting that process needing removal. I'll track them down and excise them.

This is where having a rebuilt test suite would be great ;)
