### ISSUE TITLE
Documentation is not clear on Droplets

### ISSUE THREAD

**Issue by roland-jungwirth** [whythawk/full-stack-fastapi-postgresql#24]
I am trying to deploy the "default" stack to DigitalOcean. After reading the documentation - https://github.com/whythawk/full-stack-fastapi-postgresql/blob/master/docs/deployment-guide.md - it is not clear whether this is running on just one Droplet, or whether I need to set up two (one as a Swarm manager and one as a worker)?

Also, in regards to the "neo4j" comment - is this for the manager or the worker?

**Comment by turukawa** [comment]
Hi @roland-jungwirth 

You should deploy to a single droplet. I've never tried splitting it, so can't advise as to how to go about doing that.

Re the neo4j comment, I'm assuming you mean for scaling the droplet? That's for the whole image which runs Java. If you know a more frugal image or setup, go for it, but out of my skillset.

I deployed a default version on a single 4Gb droplet at https://whyqd.com, if you want to see one running.

**Comment by roland-jungwirth** [comment]
Hi @turukawa , thank you, that helps.
