### ISSUE TITLE
WebSocket connection to 'ws://localhost:4000/ws' failed

### ISSUE THREAD

**Issue by shroominic** [whythawk/full-stack-fastapi-postgresql#31]
<img width="837" alt="Screenshot 2023-06-26 at 12 09 44" src="https://github.com/whythawk/full-stack-fastapi-postgresql/assets/34897716/1a3bef03-7f71-48b1-b5f5-451fd070c054">

I don't know what is happening or where this is coming from but the client is constantly trying to connect to this web socket and failing ...

**Comment by turukawa** [comment]
There is a placeholder for websockets (in [apiCore](https://github.com/whythawk/full-stack-fastapi-postgresql/blob/bc0b74cb1d1596e832780f5f9a980a7949829db1/%7B%7Bcookiecutter.project_slug%7D%7D/frontend/api/core.ts#L6)) but I'm not sure what could be calling it. So ... it's probably not the stack.

What it could be is the hot-reload in the Nuxt dev environment which does use sockets to check for code changes. You might want to try refreshing your Nuxt / yarn install (delete the `.nuxt` and `node_modules` folders in `frontend` and then `yarn install` again).

**Comment by shroominic** [comment]
<img width="307" alt="Screenshot 2023-06-28 at 12 51 55" src="https://github.com/whythawk/full-stack-fastapi-postgresql/assets/34897716/ee20daf2-94d9-4f4f-8a5f-9039eeddc81f">

Thanks, it was something nuxt related so I fixed it by putting `watch: false,` inside the nuxt.config.ts/content dict
