### ISSUE TITLE
Interest in Pydantic 2.0

### ISSUE THREAD

**Issue by turukawa** [whythawk/full-stack-fastapi-postgresql#33]
With the latest update to FastAPI, there is now support for Pydantic 2.0. Is there interest for an update of this stack to support it?

**Comment by turukawa** [comment]
The next update to this stack will go to `inboard 0.51` which is one step before `fastapi 0.100` and `pydantic 2.0`. Lots of updates. 

My assumption is that, since this is a starter stack, backwards compatibility is not required.

You can review the pull request https://github.com/whythawk/full-stack-fastapi-postgresql/pull/35 to see the changes before they're completed.

**Comment by hrehfeld** [comment]
Can this be closed?

**Comment by turukawa** [comment]
@hrehfeld Hi, yes, will do ...
