### ISSUE TITLE
Commented COPY in backend.docker

### ISSUE THREAD

**Issue by a-vorobyoff** [whythawk/full-stack-fastapi-postgresql#38]
Why is "COPY ./app/ /app/" commented out in backend.dockerfile? I wasted some time trying to find the problem.

**Comment by a-vorobyoff** [comment]
Yes, Alembic. Additionally, I think it would be helpful to mention in the documentation that the project has switched from Poetry to Hatch. I was a bit confused when reading the original README.md and trying to set up the environment in my IDE. A big thank you for continuing to support the project!

**Comment by turukawa** [comment]
OK, fixed and tested. 

Re Hatch, it's in the release notes for [0.7.4,](https://github.com/whythawk/full-stack-fastapi-postgresql/releases/tag/0.7.4) and [here](https://github.com/whythawk/full-stack-fastapi-postgresql#more-details). I had hassles with integrating this and that's probably where this particular error happened.
