### ISSUE TITLE
Some more found issues

### ISSUE THREAD

**Issue by a-vorobyoff** [whythawk/full-stack-fastapi-postgresql#39]
1. Vite trying to connect with Nuxt on port 24678 for hot reloading code changes – spamming webconsole log and don't work. Need expose in docker-compose.override.yml
ports:
      - "24678:24678"

2. Content loading in Nuxt don't work because of Nuxt do request on /api/_content but it routed by traefik on backend instead of frontend.
I change PathPrefix(`/api`) to  PathPrefix(`/api/v`) in docker-compose.override.yml of backend setting. Now /api/ will route to frontend.

3. When trying register with only an email by magic link, it failed:
File "/app/app/crud/crud_user.py", line 19, in create
    hashed_password=get_password_hash(obj_in.password),
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
because password don't exist. Some fix:
    hashed_password=get_password_hash(obj_in.password) if obj_in.password is not None else None,

Hope this help fix some bugs.

**Comment by turukawa** [comment]
@a-vorobyoff this is great, thank you :)

You're also welcome to do a pull request, otherwise I'll pull these through myself.
